name: "Flake - Update"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure SSH Key
        env:
          SSH_KEY: ${{ secrets.NIX_SECRETS_PRIVATE_KEY }}
        run: |
          # Create the .ssh directory safely
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the private key to a file and restrict permissions
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the destination host to known_hosts to prevent interactive prompts
          ssh-keyscan -H "github.com" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update Flake.lock file
        id: update
        uses: DeterminateSystems/update-flake-lock@v29
        with:
          token: ${{ github.token }}

      - name: Merge new Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --auto --merge ${{ steps.update.outputs.pull-request-number }}

